/*!
 * StatPlay - entry point
 * Copyright (c) 2026 Sasai Lab * Licensed under CC BY-NC 4.0.
 */
import { initPrefs } from './modules/prefs.js';
import { initHero } from './modules/hero.js';
import { initReveal } from './modules/reveal.js';
import { initNav } from './modules/nav.js';
import { initStdnorm } from './modules/stdnorm.js';
import { initNormal } from './modules/normal.js';
import { initMorep } from './modules/morep.js';
import { initProb } from './modules/prob.js';
import { initClt } from './modules/clt.js';
import { initLln } from './modules/lln.js';
import { initCi } from './modules/ci.js';
import { initHtest } from './modules/htest.js';
import { initDist } from './modules/dist.js';
import { initChitest } from './modules/chitest.js';
import { initAnova } from './modules/anova.js';
import { initCorr, initCorrAnscombe } from './modules/corr.js';
import { initReg } from './modules/reg.js';
import { initBayes } from './modules/bayes.js';
import { initErrs } from './modules/errs.js';
import { initMreg, initMregVs } from './modules/mreg.js';
import { initProptest } from './modules/proptest.js';
import { initAutorun } from './modules/autorun.js';
import { initShare } from './modules/share.js';
import { initUrlParams } from './modules/urlParams.js';
import { initLang } from './modules/lang.js';
import { initTheme } from './modules/theme.js';
import { initGraphDrag } from './modules/graphDrag.js';
import { initAnchor } from './modules/anchor.js';
import { initA11y } from './modules/a11y.js';
import { initToc } from './modules/toc.js';
import { initScrolltop } from './modules/scrolltop.js';
import { initVersion } from './modules/version.js';
import { initPwa } from './modules/pwa.js';
import { initTables } from './modules/tables.js';

initPrefs();
initHero();
initReveal();
initNav();
initStdnorm();
initNormal();
initMorep();
initProb();
initClt();
initLln();
initCi();
initHtest();
initProptest();
initDist();
initChitest();
initAnova();
initCorr();
initCorrAnscombe();
initReg();
initBayes();
initErrs();
initMreg();
initMregVs();
initAutorun();
initShare();
initUrlParams();
initLang();
initTheme();
initGraphDrag();
initAnchor();
initA11y();
initToc();
initScrolltop();
initVersion();
initPwa();
initTables();
